guestbook/urls.py
from django.conf.urls import patterns, include, url

from engine.views import HomeView, EventListView, GuestListView, EventGuestListView, GuestSignInView, EventCreateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'guestbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^events/$', EventListView.as_view(), name='events'),
    url(r'^events/guests/(?P<pk>\d+)/$', EventGuestListView.as_view(), name='events-guest-list'),
    url(r'^events/guests/add/$', EventCreateView.as_view(), name='event-create'),

    url(r'^guests/', GuestListView.as_view(), name='guests'),
    url(r'^guest/sign/(?P<pk>\d+)/$', GuestSignInView.as_view(), name='guest-sign-in'),

)

engine/models.py
from django.db import models

# Create your models here.


class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400, null=True)

    def __unicode__(self):
        return self.name


class Guest(models.Model):
    event = models.ForeignKey(Event, null=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

engine/forms.py
from django import forms


class EventCreateForm(forms.Form):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))

class GuestSignInForm(forms.Form):
    first_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))

engine/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView

from engine.models import Event, Guest
from engine.forms import GuestSignInForm, EventCreateForm

# Create your views here.

class HomeView(TemplateView):
    template_name = 'engine/home.html'

    def get_context_data(self, **kwargs):

        return {
            'home_view': True,
            'events_view': False,
            'guests_view': False,
        }


class EventListView(TemplateView):
    template_name = 'engine/events.html'

    def get_context_data(self, **kwargs):

        return {
            'home_view': False,
            'events_view': True,
            'guests_view': False,
            'events': Event.objects.all(),
        }


class EventGuestListView(TemplateView):
    template_name = 'engine/event_guest_list.html'

    def dispatch(self, request, *args, **kwargs):

        try:
            event = Event.objects.get(pk=kwargs.get('pk'))

        except Event.DoesNotExist:
            return redirect('events')

        kwargs['event'] = event

        return super(EventGuestListView, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):

        return {
            'event': kwargs.get('event'),
            'guest_list': Guest.objects.filter(event=kwargs.get('event')),
        }


class GuestListView(TemplateView):
    template_name = 'engine/guests.html'

    def get_context_data(self, **kwargs):

        return {
            'home_view': False,
            'events_view': False,
            'guests_view': True,
            'guests': Guest.objects.all(),
        }


class GuestSignInView(FormView):
    form_class = GuestSignInForm
    template_name = 'engine/guest_signin_form.html'
    success_url = '/guests/'
    event = None

    def dispatch(self, request, *args, **kwargs):

        try:
            event = Event.objects.get(pk=kwargs.get('pk'))

        except Event.DoesNotExist:
            return redirect('events')

        self.event = event

        return super(GuestSignInView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        context = super(GuestSignInView, self).get_context_data(**kwargs)
        context['event'] = self.event

        return context

    def form_valid(self, form):
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        email = form.cleaned_data.get('email')

        guest = Guest.objects.create(event=self.event, first_name=first_name, last_name=last_name, email=email)
        guest.save()

        return super(GuestSignInView, self).form_valid(form)


class EventCreateView(FormView):
    form_class = EventCreateForm
    template_name = 'engine/event_create.html'
    success_url = '/events/'

    def form_valid(self, form):
        name = form.cleaned_data.get('name')

        event = Event.objects.create(name=name)
        event.save()

        return super(EventCreateView, self).form_valid(form)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Guestbook</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guestbook-app.css' %}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Django Guestbook</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if home_view %}class="active"{% endif %}"><a href="{% url 'home' %}">Home</a></li>
            <li {% if events_view %}class="active"{% endif %}><a href="{% url 'events' %}">Events</a></li>
            <li {% if guests_view %}class="active"{% endif %}><a href="{% url 'guests' %}">Guests</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/engine/event_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container content-container">
        <div class="row">
            <div class="col-xs-12">

                <h1>This is where we'll create an event.</h1>

                <form action="{% url 'event-create' %}" method="post" role="form">

                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_name">Event Name</label>
                        {{ form.name }}
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>

                </form>


            </div>
        </div> <!--/row-->
    </div> <!--/container-->





{% endblock %}

templates/engine/event_guest_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container content-container">

        <h1>Guest List for {{ event.name }}</h1>

        {% if guest_list %}

          <ul class="list-group">

            {% for guest in guest_list %}
                <li class="list-group-item"><a href="mailto:{{ guest.email }}">{{ guest.first_name }}&nbsp;{{ guest.last_name }}</a></li>
            {% endfor %}

          </ul>

        {% else %}

          <p class="lead">There are no guests signed in for this event.</p>

        {% endif %}

        <p><a class="btn btn-primary" href="{% url 'guest-sign-in' event.id %}">Sign this Guestbook</a></p>

    </div><!-- /.container -->

{% endblock %}
        

templates/engine/events.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container content-container">

        <h1>Events</h1>

        {% if events %}

          <a href="{% url 'event-create' %}">Create New Event</a>

          <div>&nbsp;</div>

          <ul class="list-group">

            {% for event in events %}
                <li class="list-group-item"><a href="{% url 'events-guest-list' event.id %}">{{ event.name }}</a></li>
            {% endfor %}

          </ul>

        {% else %}

          <p class="lead">There are no events in the system.</p>
          <p><a href="{% url 'event-create' %}" class="btn btn-primary">Add New Event</a></p>

        {% endif %}

    </div><!-- /.container -->

{% endblock %}

templates/engine/guest_signin_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">

                <h1>Sign Into {{ event }}</h1>


                <form action="{% url 'guest-sign-in' event.id %}" method="POST" role="form">

                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_first_name">First Name</label>
                        {{ form.first_name }}
                    </div>

                    <div class="form-group">
                        <label for="id_last_name">Last Name</label>
                        {{ form.last_name }}
                    </div>

                    <div class="form-group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>

                </form>




            </div>
        </div> <!--/row-->
    </div> <!--/container-->





{% endblock %}

templates/engine/guests.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container content-container">

        <h1>Guests</h1>

        {% if guests %}

          <ul class="list-group">

            {% for guest in guests %}
                <li class="list-group-item"><a href="mailto:{{ guest.email }}">{{ guest.first_name }}&nbsp;{{ guest.last_name }}</a></li>
            {% endfor %}

          </ul>

        {% else %}

          <p class="lead">There are no guests in the system.</p>

        {% endif %}

    </div><!-- /.container -->

{% endblock %}

templates/engine/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container content-container">


        <h1>Django Guestbook</h1>
        <p class="lead">A simple guestbook framework built in Python/Django.</p>


    </div><!-- /.container -->

{% endblock %}